# [1] DB 연결 설정 (MySQL - GCP Cloud SQL 내부 IP 사용)
spring.datasource.url=jdbc:mysql://10.54.192.3:3306/capstone_db?useSSL=false&serverTimezone=Asia/Seoul
spring.datasource.username=docherri
spring.datasource.password=hansung
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# [2] JPA 자동 테이블 생성/수정
spring.jpa.hibernate.ddl-auto=update

# [3] SQL 출력 (디버깅용)
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG

# [4] 서버 포트 설정 (필요 시)
server.port=8080

# [5] UTF-8 인코딩
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true


spring.security.user.name=docherri
spring.security.user.password=hansung123
app.api-key=cpstone2025stepup
